# Generated by Django 5.0.6 on 2024-07-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(default='IT', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
