# Generated by Django 5.0.2 on 2024-07-26 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afb_network.employeeprofile'),
        ),
    ]
