# Generated by Django 5.0.2 on 2024-07-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0002_timeentry_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afb_network.employeeprofile'),
        ),
    ]
