# Generated by Django 5.0.2 on 2024-07-26 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0003_remove_event_creator_event_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, to='afb_network.employeeprofile'),
        ),
    ]
