# Generated by Django 5.0.6 on 2024-07-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0004_department_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
