# Generated by Django 5.0.2 on 2024-07-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0007_event_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='users',
            new_name='user',
        ),
    ]
