# Generated by Django 5.0.6 on 2024-07-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0008_department_key_documents_alter_employeeprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='key_documents',
            field=models.FileField(blank=True, null=True, upload_to='department_documents/'),
        ),
    ]
