# Generated by Django 5.0.6 on 2024-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0009_alter_department_key_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='department_curriculum/'),
        ),
        migrations.AddField(
            model_name='department',
            name='faqs',
            field=models.FileField(blank=True, null=True, upload_to='department_faqs/'),
        ),
        migrations.AddField(
            model_name='department',
            name='goals',
            field=models.FileField(blank=True, null=True, upload_to='department_goals/'),
        ),
    ]
