# Generated by Django 5.0.2 on 2024-07-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0010_department_curriculum_department_faqs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
