# Generated by Django 5.0.2 on 2024-07-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afb_network', '0011_alter_employeeprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
